<?php

namespace App\Services\Themes;

/**
 * `select` options in a theme manifest may be bare strings (legacy manifests) or
 * `{value, label}` objects (generated by the frontend section library). Every
 * validator/coercer goes through this helper so both forms are accepted everywhere.
 */
final class SchemaOptions
{
    /** @return list<string> the allowed option values, whatever the manifest shape */
    public static function values(mixed $options): array
    {
        if (! is_array($options)) {
            return [];
        }
        $values = [];
        foreach ($options as $option) {
            if (is_string($option) || is_int($option) || is_float($option)) {
                $values[] = (string) $option;
            } elseif (is_array($option) && array_key_exists('value', $option) && is_scalar($option['value'])) {
                $values[] = (string) $option['value'];
            }
        }

        return $values;
    }

    /** True when every option is a bare scalar or a `{value, label}` object. */
    public static function isWellFormed(mixed $options): bool
    {
        if (! is_array($options)) {
            return false;
        }
        foreach ($options as $option) {
            $ok = is_scalar($option)
                || (is_array($option) && array_key_exists('value', $option) && is_scalar($option['value']));
            if (! $ok) {
                return false;
            }
        }

        return true;
    }

    public static function contains(mixed $options, mixed $value): bool
    {
        return is_scalar($value) && in_array((string) $value, self::values($options), true);
    }
}
